### PR TITLE
document open-files metric

### PR DESCRIPTION
**Pull request by francisdb**

### CODE REVIEW

**Comment by francisdb** [comment]
did not touch anything else than the README?

**Comment by mboye** [comment]
It looks like the tests are not robust enough. Tests are failing randomly in my PR (#11) too.

**Comment by dpsoft** [comment]
@francisdb  could you please [electronically sign](https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform) the CLA for us to merge this? thanks!

**Comment by francisdb** [comment]
@dpsoft I got "Hemos registrado tu respuesta."

**Comment by ivantopo** [comment]
Hey @francisdb, I'm closing the PR because we are moving all the code to the main Kamon repository and we will centralize all documentation on the website. Thanks for the effort!

**Pull request closed without merging**
